spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/Desktop/WebApp_springJPA/H2/bin/datajpa
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 200
logging.level:
  org.hibernate.SQL: debug
  #org.hibernate.type: trace

